### ISSUE TITLE
Issue in 1.0.5 | error TS2339: Property 'ɵNgxsFeatureModule' does not exist on type

### ISSUE THREAD

**Issue by swarnadeepsaha** [ngxs-labs/actions-executing#20]
```
Error: node_modules/@ngxs-labs/actions-executing/lib/actions-executing.module.d.ts:7:89 - error TS2339: Property 'ɵNgxsFeatureModule' does not exist on type 'typeof import("<project-dir>/node_modules/@ngxs/store/ngxs-store")'.

7     static ɵmod: i0.ɵɵNgModuleDeclaration<NgxsActionsExecutingModule, never, [typeof i1.ɵNgxsFeatureModule], never>;
```

We were using ^1.0.3
Fixed when disallow patch upgrade i.e. from `^1.0.3` to `1.0.3`

**Comment by joaqcid** [comment]
@swarnadeepsaha  what version of `@ngxs/store` are you using?

**Comment by swarnadeepsaha** [comment]
@joaqcid 
"@ngxs/store": "3.7.6"
"@angular/core": "^14.2.12"

**Comment by joaqcid** [comment]
@swarnadeepsaha  right, you could try again using the `^1.0.3`, latest version should work now

**Comment by swarnadeepsaha** [comment]
@joaqcid doesn't work with 1.0.6 (^1.0.3)

```
Error: Cannot resolve type entity i1.ɵNgxsFeatureModule to symbol

Error: node_modules/@ngxs-labs/actions-executing/lib/actions-executing.module.d.ts:7:89 - error TS2339: Property 'ɵNgxsFeatureModule' does not exist on type 'typeof import("<project-dir>/node_modules/@ngxs/store/ngxs-store")'.

7     static ɵmod: i0.ɵɵNgModuleDeclaration<NgxsActionsExecutingModule, never, [typeof i1.ɵNgxsFeatureModule], never>;
```

**Comment by joaqcid** [comment]
ok, so you should use `1.0.4`, on that version `actions-executing` was compiled using that `@ngxs/store` `3.7.6`
